### ISSUE TITLE
So where are all the developers now?

### ISSUE THREAD

**Issue by bweir** [WP1125/Alone#2]
I haven't seen any activity on this repository!

**Comment by WP1125** [comment]
Everything such as ai and charactet stuff is being made. It just hasn't
been merged yet.I'll have someone on it this week

**Comment by rodrigih** [comment]
Hi Brett. 
William assigned me to manage the repository. I have a workflow model in mind and will implement it as soon as I discuss things with William. If you have any suggestions/advice in terms of the workflow model, I'll gladly appreciate it.
